/-
Copyright (c) 2026 Shanwen Wang, Yijun Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yijun Yuan
-/

import PAdicOrderType.Puiseux.PAdicStrictPuiseux

/-!
# Puiseux approximation by finite truncations

Every Teichmüller monomial belongs to the strict `p`-adic Puiseux field. If an
algebraic series has finite support below every rational bound, its finite
truncations approximate it by Puiseux elements. Krasner’s lemma then places
the series itself in the field generated by one sufficiently close truncation.

This is the converse direction in the proof of Proposition 4.3. The argument is independent
of the support order-type dichotomy.
-/

namespace PAdicOrderType

open TrustworthyKedlaya pAdicHahnSeries
open scoped IntermediateField

variable {p : ℕ} [Fact (Nat.Prime p)]

/-- Every Teichmüller monomial is a Puiseux series, by the coefficient characterization. -/
private lemma exists_pAdicStrictPuiseux_coe_eq_single (q : ℚ) (a : 𝔽ᵃ_[p]) :
    ∃ x : pAdicStrictPuiseux p, single q a = (x : 𝕃_[p]) := by
  apply (exists_pAdicStrictPuiseux_iff _).mpr
  constructor
  · refine ⟨⟨q.den, q.den_pos⟩, fun r hr => ?_⟩
    have hrq : r = q := by
      by_contra h
      exact hr (by change (single q a).coeff r = 0; rw [coeff_single]; simp [h])
    subst r
    change ((q.den : ℚ) * q).isInt = true
    rw [Rat.den_mul_eq_num]
    simp [Rat.isInt]
  · apply ((Set.finite_singleton 0).insert a).subset
    rintro b ⟨r, rfl⟩
    rw [coeff_single]
    dsimp only
    split_ifs <;> simp

/-- An element of the algebraic closure whose Hahn support is finite below every
rational cutoff lies in the strict p-adic Puiseux field.

Finite truncations are Puiseux elements and converge to the given element. **Krasner's lemma**
places it in the field generated by one sufficiently close truncation, as in the proof of
Proposition 4.3. -/
lemma mem_pAdicStrictPuiseux_of_finite_support_below (a : PadicAlgCl p)
    (hfin : ∀ r : ℚ, ((a : 𝕃_[p]).support ∩ Set.Iio r).Finite) : a ∈ pAdicStrictPuiseux p := by
  classical
  have hint : IsIntegral ℚ_[p] a := (Algebra.IsAlgebraic.isAlgebraic a).isIntegral
  -- Separate `a` from its finitely many other conjugates.
  have hconj : {a' : PadicAlgCl p | IsConjRoot ℚ_[p] a a' ∧ a' ≠ a}.Finite :=
    ((minpoly ℚ_[p] a).rootSet_finite (PadicAlgCl p)).subset
      fun c hc => (isConjRoot_iff_mem_minpoly_rootSet hint).mp hc.1
  obtain ⟨ε, hε, hball⟩ :=
    Metric.isOpen_iff.mp hconj.isClosed.isOpen_compl a fun h => h.2 rfl
  have hp : (1 : ℝ) < p := by exact_mod_cast (Fact.out : p.Prime).one_lt
  obtain ⟨n, hn⟩ := exists_pow_lt_of_lt_one hε
    (show (p : ℝ)⁻¹ < 1 from inv_lt_one_of_one_lt₀ hp)
  -- The truncation below `n` is a finite sum of Puiseux monomials.
  choose y hy using fun q : ℚ => exists_pAdicStrictPuiseux_coe_eq_single q ((a : 𝕃_[p]).coeff q)
  let x : pAdicStrictPuiseux p := ∑ q ∈ (hfin n).toFinset, y q
  have hx : (x : 𝕃_[p]) =
      ∑ q ∈ (hfin n).toFinset, single q ((a : 𝕃_[p]).coeff q) := by
    let g : pAdicStrictPuiseux p →+* 𝕃_[p] :=
      (algClEmbd p).toRingHom.comp (pAdicStrictPuiseux p).subtype
    rw [coe_coe]
    change g x = _
    dsimp only [x]
    rw [map_sum]
    apply Finset.sum_congr rfl
    intro q hq
    exact (coe_coe (y q).val).symm.trans (hy q).symm
  have happrox : ‖a - x.val‖ < ε := by
    have hnorm : ‖a - x.val‖ = ‖(a : 𝕃_[p]) - (x : 𝕃_[p])‖ := by
      rw [coe_coe, coe_coe, ← map_sub, norm_algClEmbd]
    rw [hnorm, hx]
    have hval := le_val_sub_sum_support_below (p := p) (a : 𝕃_[p]) (n : ℚ) (hfin n)
    apply lt_of_le_of_lt ((norm_le_iff_le_val (p := p)).mpr hval)
    simpa [Real.rpow_neg, Real.rpow_natCast, inv_pow] using hn
  -- Krasner gives `ℚ_[p](a) ⊆ ℚ_[p](x)`, hence membership in the Puiseux field.
  have hmem : a ∈ IntermediateField.adjoin ℚ_[p] {x.val} := by
    refine IsKrasner.krasner (minpoly.irreducible hint).separable (IsAlgClosed.splits _)
      (Algebra.IsAlgebraic.isAlgebraic x.val).isIntegral fun a' hc hne =>
        happrox.trans_le ?_
    have hnb : a' ∉ Metric.ball a ε := fun h => hball h ⟨hc, hne.symm⟩
    rw [Metric.mem_ball, not_lt] at hnb
    calc
      ε ≤ dist a' a := hnb
      _ = ‖a - a'‖ := by rw [dist_comm, dist_eq_norm]
  let K : IntermediateField ℚ_[p] (PadicAlgCl p) :=
    (⨆ T : ℕ+, ℚᵘⁿ_[p]⟮pRadical p T⟯).restrictScalars ℚ_[p]
  exact (IntermediateField.adjoin_simple_le_iff.mpr (show x.val ∈ K from x.property)) hmem

end PAdicOrderType
